import numpy as np

from robosuite.models.robots.manipulators.manipulator_model import ManipulatorModel
from robosuite.utils.mjcf_utils import xml_path_completion


class TiagoProRight(ManipulatorModel):
    """
    Right arm of the TIAGo Pro (PAL Robotics), mounted on the (frozen) torso of the mobile base.

    Single-arm API (``arms == ["right"]``, action_dim 7 with the PAL Pro gripper: OSC_POSE delta (6) + gripper (1)), so
    observation keys / sensor names are identical to Panda's (robot0_eef_pos, robot0_eef_quat, robot0_gripper_qpos,
    robot0_eye_in_hand_image, gripper0_right_force_ee/torque_ee).

    The model (``robots/tiago_pro/robot_right.xml``) is GENERATED by ``tools/tiago_pro/convert_tiago_pro.py``: base,
    wheels, torso, head and the left arm (with its gripper closed, in a dedicated park pose) are frozen at the poses in
    ``tools/tiago_pro/overlay.py`` (PARK_TORSO, PARK_HEAD, LEFT_PARK); only the 7 right arm joints are actuated.
    ``init_qpos``, ``base_xpos_offset``, ``top_offset`` and ``_horizontal_radius`` come from the reach study
    ``tools/tiago_pro/find_init_qpos.py``.

    Args:
        idn (int or str): Number or some other unique identification string for this robot instance
    """

    arms = ["right"]

    def __init__(self, idn=0):
        super().__init__(xml_path_completion("robots/tiago_pro/robot_right.xml"), idn=idn)

    @property
    def default_base(self):
        return "NoActuationBase"

    @property
    def default_gripper(self):
        return {"right": "PalProGripper"}

    @property
    def default_controller_config(self):
        return {"right": "default_tiagoproright"}

    @property
    def init_qpos(self):
        return np.array(INIT_QPOS)

    @property
    def base_xpos_offset(self):
        # The right arm mount sits at (+0.065, -0.159) in the base frame, so the base is shifted by +0.159 in y to put the
        # shoulder on the table centre line. x: base collision extent (x +-0.358, y +-0.248) clears the table edge by TABLE_GAP.
        # "bins" / "empty" align the shoulder with Panda's mount (bins: the base front stays clear of the 0.39 m deep table).
        return {
            "bins": (-0.58, -0.1 + SHOULDER_Y, 0),
            "empty": (-0.6 - SHOULDER_X, SHOULDER_Y, 0),
            "table": lambda table_length: (-(table_length / 2 + BASE_FRONT_EXTENT + TABLE_GAP), BASE_Y_OFFSET, 0),
        }

    @property
    def top_offset(self):
        return np.array((0, 0, 1.0))

    @property
    def _horizontal_radius(self):
        return HORIZONTAL_RADIUS

    @property
    def arm_type(self):
        return "single"

    @property
    def _eef_name(self):
        return {"right": "right_hand"}


# Constants below are set by tools/tiago_pro/find_init_qpos.py (reach study) and cross-checked by
# tests/test_robots/test_tiago_pro_consistency.py against tools/tiago_pro/overlay.py.
INIT_QPOS = [-2.5965, -1.3022, 1.0465, -1.8428, 2.2129, 1.4721, 0.8143]
BASE_FRONT_EXTENT = 0.358  # base collision extent along x
TABLE_GAP = 0.02  # clearance between the base front and the table edge
BASE_Y_OFFSET = 0.159  # = |arm mount y| (0.15918): right shoulder on the table centre line
SHOULDER_X, SHOULDER_Y = 0.065, 0.159  # arm mount in the base frame (x, |y|)
HORIZONTAL_RADIUS = 0.5
