"""
Drift protection for the generated TIAGo Pro assets. No xacro / PAL clones needed: the committed menagerie-style package
(``robots/tiago_pro/pal_tiago_pro``) is compared with the committed robosuite files (``robot_right.xml``,
``pal_pro_gripper.xml``) and with the hand-maintained python constants (TiagoProRight, PalProGripper, controller JSON,
``tools/tiago_pro/overlay.py``).

$ pytest -s tests/test_robots/test_tiago_pro_consistency.py
"""
import json
import os
import re
import sys

import mujoco
import numpy as np
import pytest

import robosuite
from robosuite.models.base import MujocoXML
from robosuite.models.grippers import PalProGripper
from robosuite.models.robots.manipulators import tiago_pro_right_robot as tpr

ASSETS = os.path.join(os.path.dirname(robosuite.__file__), "models", "assets")
TIAGO = os.path.join(ASSETS, "robots", "tiago_pro")
PKG = os.path.join(TIAGO, "pal_tiago_pro")
GRIPPER_XML = os.path.join(ASSETS, "grippers", "pal_pro_gripper.xml")
REPO = os.path.abspath(os.path.join(os.path.dirname(robosuite.__file__), ".."))
OTYPE = mujoco.mjtObj


def nm(m, t, i):
    return mujoco.mj_id2name(m, t, i) or ""


@pytest.fixture(scope="module")
def ov():
    tools = os.path.join(REPO, "tools", "tiago_pro")
    if not os.path.isdir(tools):
        pytest.skip("tools/tiago_pro is not part of the installed package")
    sys.path.insert(0, tools)
    try:
        import overlay
    finally:
        sys.path.remove(tools)
    return overlay


@pytest.fixture(scope="module")
def pkg():
    m = mujoco.MjModel.from_xml_path(os.path.join(PKG, "tiago_pro.xml"))
    return m, mujoco.MjData(m)


@pytest.fixture(scope="module")
def merged():
    """robot_right.xml + gripper merged the way robosuite does it (flat defaults, MujocoXML loader)."""

    # a PalProGripper instance merged into the robot at right_hand, like ManipulatorModel.add_gripper
    rob = MujocoXML(os.path.join(TIAGO, "robot_right.xml"))
    g = PalProGripper(idn="0_right")
    rob.merge(g, merge_body="right_hand")
    m = rob.get_model()
    return m, mujoco.MjData(m)


def pkg_set(pm, pd, q_arm, ov, finger=None):
    pd.qpos[:] = pm.qpos0
    pd.qpos[2] = 0.0  # robot_right sits on the floor (package root is 2 mm above it)
    j = lambda n: pm.jnt_qposadr[mujoco.mj_name2id(pm, OTYPE.mjOBJ_JOINT, n)]
    pd.qpos[j("torso_lift_joint")] = ov.PARK_TORSO
    pd.qpos[j("head_1_joint")], pd.qpos[j("head_2_joint")] = ov.PARK_HEAD
    for i, v in enumerate(ov.LEFT_PARK):
        pd.qpos[j("arm_left_%d_joint" % (i + 1))] = v
    pd.qpos[j("gripper_left_finger_joint")] = ov.PARK_LEFT_GRIPPER
    for i in range(7):
        pd.qpos[j("arm_right_%d_joint" % (i + 1))] = q_arm[i]
    if finger is not None:
        pd.qpos[j("gripper_right_finger_joint")] = finger
        for e in range(pm.neq):
            if pm.eq_type[e] == 2 and nm(pm, OTYPE.mjOBJ_JOINT, pm.eq_obj2id[e]).startswith("gripper_right"):
                pd.qpos[j(nm(pm, OTYPE.mjOBJ_JOINT, pm.eq_obj2id[e]))] = finger / pm.eq_data[e, 1]
    mujoco.mj_forward(pm, pd)


# ------------------------------------------------------------------------------------------------------------------
def test_generated_files_are_flat_and_marked():
    for path in (os.path.join(TIAGO, "robot_right.xml"), GRIPPER_XML):
        txt = open(path).read()
        assert re.search(r"class=|childclass|<default", txt) is None, path  # robosuite's loader needs flat files
        assert "Generated by tools/tiago_pro/convert_tiago_pro.py" in txt and "Apache-2.0" in txt
        assert "../" not in txt


def test_arm_joints_match_package(pkg):
    pm, _ = pkg
    r = mujoco.MjModel.from_xml_path(os.path.join(TIAGO, "robot_right.xml"))
    names = ["arm_right_%d_joint" % i for i in range(1, 8)]
    assert [nm(r, OTYPE.mjOBJ_JOINT, j) for j in range(r.njnt)] == names
    for j, n in enumerate(names):
        pj = mujoco.mj_name2id(pm, OTYPE.mjOBJ_JOINT, n)
        assert pj >= 0
        for field in ("jnt_range", "jnt_axis", "jnt_actfrcrange", "jnt_type", "jnt_limited"):
            assert np.allclose(getattr(r, field)[j], getattr(pm, field)[pj]), (n, field)
        rd_, pd_ = r.jnt_dofadr[j], pm.jnt_dofadr[pj]
        assert r.dof_damping[rd_] == pytest.approx(pm.dof_damping[pd_])
        assert r.dof_frictionloss[rd_] == pytest.approx(pm.dof_frictionloss[pd_])
    # torque motors with the URDF efforts as ctrlrange
    assert r.nu == 7 and r.na == 0
    assert np.allclose(r.actuator_ctrlrange[:, 1], r.jnt_actfrcrange[:, 1])
    assert np.allclose(r.actuator_ctrlrange[:, 1], [43, 43, 26, 26, 26, 26, 26])
    assert not any(k in nm(r, OTYPE.mjOBJ_ACTUATOR, u) for u in range(r.nu) for k in ("torso", "mobile", "head", "leg"))


def test_masses_and_collision_geoms_match_package(pkg):
    pm, _ = pkg
    r = mujoco.MjModel.from_xml_path(os.path.join(TIAGO, "robot_right.xml"))
    shared = 0
    for b in range(1, r.nbody):
        n = nm(r, OTYPE.mjOBJ_BODY, b)
        pb = mujoco.mj_name2id(pm, OTYPE.mjOBJ_BODY, "arm_right_tool_link" if n == "right_hand" else n)
        if pb < 0 or n == "right_hand":
            continue
        shared += 1
        assert r.body_mass[b] == pytest.approx(pm.body_mass[pb], rel=1e-9, abs=1e-12), n
        assert np.allclose(r.body_inertia[b], pm.body_inertia[pb], rtol=1e-6, atol=1e-12), n
    assert shared > 40
    # same gripper mass left over: robot_right + right gripper subtree == package
    gb = mujoco.mj_name2id(pm, OTYPE.mjOBJ_BODY, "gripper_right_base_link")
    assert r.body_mass.sum() + pm.body_subtreemass[gb] == pytest.approx(pm.body_mass.sum(), abs=1e-9)
    # per-geom attributes of the collision geoms (names are shared): contact params, mesh, size
    n_cmp = 0
    for g in range(r.ngeom):
        name = nm(r, OTYPE.mjOBJ_GEOM, g)
        pg = mujoco.mj_name2id(pm, OTYPE.mjOBJ_GEOM, name) if name else -1
        if pg < 0:
            continue
        n_cmp += 1
        for field in ("geom_type", "geom_contype", "geom_conaffinity", "geom_condim", "geom_friction", "geom_solref",
                      "geom_solimp", "geom_margin", "geom_gap", "geom_priority"):
            assert np.allclose(getattr(r, field)[g], getattr(pm, field)[pg]), (name, field)
        if r.geom_type[g] == mujoco.mjtGeom.mjGEOM_MESH:
            assert nm(r, OTYPE.mjOBJ_MESH, r.geom_dataid[g]) == nm(pm, OTYPE.mjOBJ_MESH, pm.geom_dataid[pg])
            assert r.mesh_vertnum[r.geom_dataid[g]] == pm.mesh_vertnum[pm.geom_dataid[pg]]  # same maxhullvert
    assert n_cmp > 20
    # the contact excludes of the right arm survive in robot_right.xml
    for e in range(pm.nexclude):
        b1, b2 = pm.exclude_signature[e] >> 16, pm.exclude_signature[e] & 0xFFFF
        n1, n2 = nm(pm, OTYPE.mjOBJ_BODY, b1), nm(pm, OTYPE.mjOBJ_BODY, b2)
        i1, i2 = mujoco.mj_name2id(r, OTYPE.mjOBJ_BODY, n1), mujoco.mj_name2id(r, OTYPE.mjOBJ_BODY, n2)
        if i1 >= 0 and i2 >= 0:
            assert (min(i1, i2) << 16) + max(i1, i2) in set(r.exclude_signature.tolist()), (n1, n2)


def test_fk_of_tool_link_and_grasp_site_matches_package(pkg, merged, ov):
    pm, pd = pkg
    mm, md = merged
    rng = np.random.default_rng(0)
    lo, hi = mm.jnt_range[:7, 0], mm.jnt_range[:7, 1]
    site = lambda m, n: mujoco.mj_name2id(m, OTYPE.mjOBJ_SITE, n)
    worst = 0.0
    for _ in range(20):
        q = rng.uniform(lo, hi)
        finger = rng.uniform(0.0, 0.07)
        pkg_set(pm, pd, q, ov, finger)
        md.qpos[:] = 0
        md.qpos[:7] = q
        gj = lambda n: mm.jnt_qposadr[mujoco.mj_name2id(mm, OTYPE.mjOBJ_JOINT, "gripper0_right_" + n)]
        md.qpos[gj("finger_joint")] = finger
        for e in range(pm.neq):
            if pm.eq_type[e] == 2 and nm(pm, OTYPE.mjOBJ_JOINT, pm.eq_obj2id[e]).startswith("gripper_right"):
                jn = nm(pm, OTYPE.mjOBJ_JOINT, pm.eq_obj2id[e])
                md.qpos[gj(jn[len("gripper_right_") :])] = finger / pm.eq_data[e, 1]
        mujoco.mj_forward(mm, md)
        # tool link (= robosuite right_hand), grasp site, ft frame; robosuite robot root sits at the origin
        pairs = [
            (mujoco.mj_name2id(pm, OTYPE.mjOBJ_BODY, "arm_right_tool_link"), mujoco.mj_name2id(mm, OTYPE.mjOBJ_BODY, "right_hand"), "body"),
            (site(pm, "gripper_right_grasping_frame_Z"), site(mm, "gripper0_right_grip_site"), "site"),
            (site(pm, "gripper_right_ft_frame"), site(mm, "gripper0_right_ft_frame"), "site"),
        ]
        for pi, mi, kind in pairs:
            assert pi >= 0 and mi >= 0
            pp, pr = (pd.xpos[pi], pd.xmat[pi]) if kind == "body" else (pd.site_xpos[pi], pd.site_xmat[pi])
            mp, mr = (md.xpos[mi], md.xmat[mi]) if kind == "body" else (md.site_xpos[mi], md.site_xmat[mi])
            worst = max(worst, np.abs(pp - mp).max())
            if kind == "body":  # (site frames follow a different axis convention: PAL grasp frame x = approach)
                assert np.abs(pr - mr).max() < 1e-6
    assert worst < 1e-6, worst


def load_gripper_radian():
    """Gripper XMLs carry no <compiler>; robosuite's world (base.xml) supplies angle="radian" when it merges them."""
    spec = mujoco.MjSpec.from_file(GRIPPER_XML)
    spec.compiler.degree = False
    return spec.compile()


def test_gripper_xml_matches_package(pkg):
    pm, _ = pkg
    g = load_gripper_radian()
    assert g.nu == 1 and g.nq == 8 and g.njnt == 8
    for j in range(g.njnt):
        n = nm(g, OTYPE.mjOBJ_JOINT, j)
        pj = mujoco.mj_name2id(pm, OTYPE.mjOBJ_JOINT, "gripper_right_" + n)
        assert pj >= 0, n
        assert np.allclose(g.jnt_range[j], pm.jnt_range[pj]), n
        assert np.allclose(g.jnt_actfrcrange[j], pm.jnt_actfrcrange[pj]), n
        assert g.dof_damping[g.jnt_dofadr[j]] == pytest.approx(pm.dof_damping[pm.jnt_dofadr[pj]]), n
    pos = mujoco.MjModel.from_xml_path(os.path.join(PKG, "tiago_pro_position.xml"))  # tiago_pro.xml has no actuators
    pa = [a for a in range(pos.nu) if nm(pos, OTYPE.mjOBJ_ACTUATOR, a).startswith("gripper_right")]
    assert len(pa) == 1
    assert np.allclose(g.actuator_ctrlrange[0], pos.actuator_ctrlrange[pa[0]])
    # robosuite grippers carry an explicit actuator forcerange; in the package the joint actuatorfrcrange (+-8 N) limits it
    assert np.allclose(g.actuator_forcerange[0], pm.jnt_actfrcrange[mujoco.mj_name2id(pm, OTYPE.mjOBJ_JOINT, 'gripper_right_finger_joint')])
    assert np.allclose(g.actuator_gainprm[0, :3], pos.actuator_gainprm[pa[0], :3])
    assert np.allclose(g.actuator_biasprm[0, :3], pos.actuator_biasprm[pa[0], :3])
    # mimic equalities (polycoef) identical
    pe = {nm(pm, OTYPE.mjOBJ_JOINT, pm.eq_obj2id[e]): pm.eq_data[e, :5] for e in range(pm.neq)
          if nm(pm, OTYPE.mjOBJ_JOINT, pm.eq_obj2id[e]).startswith("gripper_right")}
    ge = {nm(g, OTYPE.mjOBJ_JOINT, g.eq_obj2id[e]): g.eq_data[e, :5] for e in range(g.neq)}
    assert len(ge) == 7
    for jn, coef in ge.items():
        assert np.allclose(coef, pe["gripper_right_" + jn])
    # finger contact parameters copied from Panda
    for gname in ("inner_finger_left_collision", "fingertip_left_collision"):
        gi = mujoco.mj_name2id(g, OTYPE.mjOBJ_GEOM, gname)
        pi = mujoco.mj_name2id(pm, OTYPE.mjOBJ_GEOM, "gripper_right_" + gname.replace("_left_", "_left_"))
        assert gi >= 0 and (pi < 0 or np.allclose(g.geom_friction[gi], pm.geom_friction[pi]))


def test_palprogripper_constants_match_xml():
    g = PalProGripper()
    xml = load_gripper_radian()
    assert g.dof == xml.nu == 1
    assert len(g.init_qpos) == len(g.joints) == xml.njnt == 8
    # init_qpos = open finger_joint + mimic joints evaluated from the equality polynomials (joint order of the xml)
    q = np.zeros(8)
    q[0] = xml.jnt_range[0, 1]
    names = [nm(xml, OTYPE.mjOBJ_JOINT, j) for j in range(8)]
    assert names[0] == "finger_joint"
    for e in range(xml.neq):
        j2 = nm(xml, OTYPE.mjOBJ_JOINT, xml.eq_obj2id[e])  # constrained (second) joint
        q[names.index(j2)] = q[0] / xml.eq_data[e, 1]
    assert np.allclose(g.init_qpos, q, atol=1e-4)
    assert xml.actuator_ctrlrange[0].tolist() == [0.0, 0.07]  # 0 = closed .. 0.07 = open
    sensors = [nm(xml, OTYPE.mjOBJ_SENSOR, s) for s in range(xml.nsensor)]
    assert sensors == ["force_ee", "torque_ee"]


def test_tiago_pro_right_constants_match_assets_and_overlay(ov, pkg, merged):
    mm, md = merged
    r = mujoco.MjModel.from_xml_path(os.path.join(TIAGO, "robot_right.xml"))
    rd = mujoco.MjData(r)
    # init_qpos inside the joint limits with margin
    q0 = np.array(tpr.TiagoProRight().init_qpos)
    assert q0.shape == (7,)
    assert np.all(q0 > r.jnt_range[:, 0] + 0.1) and np.all(q0 < r.jnt_range[:, 1] - 0.1)
    # base front extent == x extent of the base collision boxes; the arm mount sits at the baked pose
    rd.qpos[:7] = q0
    mujoco.mj_forward(r, rd)
    base_geoms = [g for g in range(r.ngeom) if nm(r, OTYPE.mjOBJ_BODY, r.geom_bodyid[g]) == "base_link" and r.geom_contype[g]]
    front = max(rd.geom_xpos[g][0] + r.geom_size[g][0] for g in base_geoms)
    half_y = max(rd.geom_xpos[g][1] + r.geom_size[g][1] for g in base_geoms)
    assert tpr.BASE_FRONT_EXTENT == pytest.approx(front, abs=2e-3)
    assert half_y == pytest.approx(0.248, abs=2e-3)
    mount = rd.xpos[mujoco.mj_name2id(r, OTYPE.mjOBJ_BODY, "torso_arm_right_link")]
    assert tpr.SHOULDER_X == pytest.approx(mount[0], abs=2e-3)
    assert tpr.BASE_Y_OFFSET == pytest.approx(-mount[1], abs=2e-3)
    # torso lift is baked at PARK_TORSO: package arm mount height at that torso == robot_right
    pm, pd = pkg
    pkg_set(pm, pd, q0, ov)
    pmount = pd.xpos[mujoco.mj_name2id(pm, OTYPE.mjOBJ_BODY, "torso_arm_right_link")]
    assert pmount[2] == pytest.approx(mount[2], abs=1e-6)
    # controller frame site is aligned with the robot base frame (x forward, y left, z up)
    sid = mujoco.mj_name2id(r, OTYPE.mjOBJ_SITE, "right_center")
    assert np.allclose(rd.site_xmat[sid].reshape(3, 3), np.eye(3), atol=1e-6)
    # wrist camera = overlay constants
    cam = mujoco.mj_name2id(r, OTYPE.mjOBJ_CAMERA, "eye_in_hand")
    assert np.allclose(r.cam_pos[cam], ov.EYE_IN_HAND_POS, atol=1e-6) and r.cam_fovy[cam] == ov.EYE_IN_HAND_FOVY
    # the fingers do not hide the grasp point: the grasp site is 0.157 m in front of the gripper base
    assert ov.GRASP_SITE_POS[2] == pytest.approx(0.157157)
    assert ov.PARK_TORSO == pytest.approx(0.35)


def test_default_controller_config_mirrors_panda_except_decoupling():
    cdir = os.path.join(os.path.dirname(robosuite.__file__), "controllers", "config", "robots")
    panda = json.load(open(os.path.join(cdir, "default_panda.json")))
    tiago = json.load(open(os.path.join(cdir, "default_tiagoproright.json")))
    pa, ta = panda["body_parts"]["arms"]["right"], tiago["body_parts"]["arms"]["right"]
    assert panda["type"] == tiago["type"] == "BASIC"
    assert list(panda["body_parts"]) == list(tiago["body_parts"]) == ["arms"]
    diff = {k: (pa[k], ta[k]) for k in pa if pa[k] != ta[k]}
    # the 7-DoF arm with the heavy gripper needs the full (coupled) task-space inertia: see README
    assert diff == {"uncouple_pos_ori": (True, False)}, diff
    assert set(pa) == set(ta)


def test_load_composite_controller_config_picks_robot_json():
    from robosuite.controllers import load_composite_controller_config

    cfg = load_composite_controller_config(controller=None, robot="TiagoProRight")
    assert cfg["body_parts"]["right"]["uncouple_pos_ori"] is False
    assert cfg["body_parts"]["right"]["type"] == "OSC_POSE"


def test_asset_size_budget():
    sizes = [os.path.getsize(os.path.join(r, f)) for r, _, fs in os.walk(PKG) for f in fs]
    gdir = os.path.join(ASSETS, "grippers", "meshes", "pal_pro_gripper")
    sizes += [os.path.getsize(os.path.join(gdir, f)) for f in os.listdir(gdir)]
    sizes += [os.path.getsize(os.path.join(TIAGO, f)) for f in os.listdir(TIAGO) if os.path.isfile(os.path.join(TIAGO, f))]
    total = sum(sizes)
    print("\nTIAGo Pro assets: %.2f MB in %d files, largest %.0f kB" % (total / 1e6, len(sizes), max(sizes) / 1e3))
    assert total <= 8.5e6  # 8.47 MB incl. 1.1 MB of gripper meshes duplicated next to grippers/pal_pro_gripper.xml
    assert max(sizes) <= 1.0e6
